name: ci

on:
  push:
    branches: [test-windows-ci]
  pull_request:
    branches: [test-windows-ci]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} ${{ matrix.os }}
    strategy:
      matrix:
        java: [8, 11]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'corretto'

      - name: clean and build
        run: ./gradlew clean build -Plog-tests --stacktrace

  lint-typescript:
    runs-on: ${{ matrix.os }}
    name: TypeScript Lint
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: cd smithy-typescript-ssdk-libs && yarn
      - name: Run eslint
        run: cd smithy-typescript-ssdk-libs && yarn lint

  test-typescript:
    runs-on: ${{ matrix.os }}
    name: TypeScript Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: cd smithy-typescript-ssdk-libs && yarn
      - name: Run tests
        run: cd smithy-typescript-ssdk-libs && yarn test

  ensure-typescript-formatted:
    runs-on: ${{ matrix.os }}
    name: Ensure TypeScript is formatted
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: cd smithy-typescript-ssdk-libs && yarn
      - name: Run the code formatter
        run: cd smithy-typescript-ssdk-libs && yarn format
      # This checks the output of git diff. If it's not empty (i.e there were
      # changes) it'll return a non-zero error code.
      - name: Ensure there are no changes from running the formatter
        run: test -z "$(git diff)"
